### ISSUE TITLE
Production build failed

### ISSUE THREAD

**Issue by plageoj** [unlight/ngx-modal#2]
When I try to build with AOT by `ng build --prod `, the compilation fails.

```
ERROR in ./node_modules/ngx-modal2/src/modal-content.component.ts
Module build failed: Error: C:\Users\plageoj\Documents\project\project\node_modules\ngx-modal2\src\modal-content.component.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\Users\plageoj\Documents\project\project\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:708:23)
    at plugin.done.then (C:\Users\plageoj\Documents\project\project\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
```

My environment is:

```
Angular CLI: 6.0.1
Node: 9.11.1
OS: win32 x64
Angular: 6.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.1
@angular/cli                      6.0.1
@angular/pwa                      0.6.1
@angular/service-worker           6.0.1
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.1
@schematics/update                0.6.1
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

**Comment by unlight** [comment]
I did not tested it with angular-cli.

But why it tries to include `ngx-modal2\src\modal-content.component.ts`? It shouldn't.
It is a source.

Try to remove src folder `ngx-modal2\src`

**Comment by plageoj** [comment]
I removed the source and then everything works. Thank you!
Could you remove these sources from NPM package?

**Comment by unlight** [comment]
I can remove, but it very helpful for development when you press "goto definition" in IDE you will see the actual source code, but not type definitions.

Can you provide your webpack configuration?
or angular-cli?

**Comment by unlight** [comment]
And your `tsconfig.json` and `tsconfig.aot.json` if any.

**Comment by unlight** [comment]
@plageoj ping

**Comment by plageoj** [comment]
I use angular-cli, and there's no `tsconfig.aot.json`. This is my `angular.json`.

```json
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "projname": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist",
            "index": "src/index.html",
            "main": "src/main.ts",
            "tsConfig": "src/tsconfig.app.json",
            "polyfills": "src/polyfills.ts",
            "assets": [
              "src/assets",
              "src/favicon.ico",
              "src/manifest.json"
            ],
            "styles": [
              "src/styles.css"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "serviceWorker": true
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "projname:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "projname:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "projname:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "karmaConfig": "./karma.conf.js",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "scripts": [],
            "styles": [
              "src/styles.css"
            ],
            "assets": [
              "src/assets",
              "src/favicon.ico",
              "src/manifest.json"
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    },
    "projname-e2e": {
      "root": "",
      "sourceRoot": "",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "./protractor.conf.js",
            "devServerTarget": "projname:serve"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "e2e/tsconfig.e2e.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
  },
  "defaultProject": "projname",
  "schematics": {
    "@schematics/angular:component": {
      "prefix": "app",
      "styleext": "css"
    },
    "@schematics/angular:directive": {
      "prefix": "app"
    }
  }
}
```

And `tsconfig.json`.

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "types": [
      "socket.io-client"
    ],
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
```

**Comment by unlight** [comment]
Npm package contains sources in src folder.
Apparently, you referencing to it instead of compiled version.
Replace
```
import {ModalComponent} from 'ngx-modal2/src/modal-content.component';
```
to
```
import {ModalComponent} from 'ngx-modal2';
```
